name: 'Maven Autosubmission'
description: 'Sets up Maven and submits your build-time dependency list to the Dependency Graph'

inputs:
  commit-ref:
    description: 'The fully-qualified git reference the analysis relates to, e.g. refs/heads/main'
    required: true
  commit-sha:
    description: 'The commit SHA to checkout and analyse'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@489441643219d2b93ee2a127b2402eb640a1b947 # v1.13.0
      with:
        checkout-ref: ${{ inputs.commit-sha }}
    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@bfd2106013da0957cdede0b6c39fb5ca25ae375e # v4.0.2
      with:
        snapshot-sha: ${{ inputs.commit-sha }}
        snapshot-ref: ${{ inputs.commit-ref }}
